export const specialChars = [82, 73, 67, 75, 82, 79, 76, 76];
export const SECRET_URL = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';
export const translations: { [key: string]: string } = {
  UNKNOWN: 'Hello!',
  CA: 'Hello!',
  CN: '你好!',
  DE: 'Hallo!',
  ES: '¡Hola!',
  FR: 'Bonjour!',
  GB: 'Hello!',
  JP: 'こんにちは!',
  KR: '안녕하세요!',
  SG: 'Hello!',
  TH: 'สวัสดี!',
  US: 'Hello!',
};
export const regionMapping: { [key: string]: string } = {
  arn1: 'Stockholm, Sweden',
  bom1: 'Mumbai, India',
  cdg1: 'Paris, France',
  cle1: 'Cleveland, USA',
  cpt1: 'Cape Town, South Africa',
  dub1: 'Dublin, Ireland',
  fra1: 'Frankfurt, Germany',
  gru1: 'São Paulo, Brazil',
  hkg1: 'Hong Kong',
  hnd1: 'Tokyo, Japan',
  iad1: 'Washington, D.C., USA',
  icn1: 'Seoul, South Korea',
  kix1: 'Osaka, Japan',
  lhr1: 'London, United Kingdom',
  pdx1: 'Portland, USA',
  sfo1: 'San Francisco, USA',
  sin1: 'Singapore',
  syd1: 'Sydney, Australia',
};
